### ISSUE TITLE
Levantamento de Componentes do Projeto

### ISSUE THREAD

**Issue by paulacresende** [Squad-1-React-Codenation/Fashionista#2]
Levantar os possíveis componentes que vão ser utilizados no aplicativo.

Documentação contendo o levantamento: https://www.notion.so/Componentes-7fe9e71d557d424cbe7416d90d700b4a

**Comment by herbertvpb** [comment]
Referência adicional proposta pela @GenildaSilva 
https://www.tobi.com/features/clothing
